version: "1"
services:
  auth:
    image: py-common/auth:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - webnet
  redis:
    image: py-common/redis:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - webnet
  mysql:
    image: py-common/redis:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    networks:
      - webnet
networks:
  webnet:
