version: "1"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: auth:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - webnet
networks:
  webnet:
